import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { auth } from '@/src/lib/firebase';
import { API_URL, cachedGet, invalidateCache, request, SellerApiError } from '@/src/services/http';
import type { SellerDocument } from '@/src/types';

export type DocumentUploadAsset={uri:string;name:string;mimeType?:string|null;size?:number|null};

function uploadForm(form:FormData,token:string,onProgress?:(value:number)=>void){return new Promise<{success:true;document:SellerDocument}>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`${API_URL}/api/seller/documents`);xhr.setRequestHeader('Accept','application/json');xhr.setRequestHeader('Authorization',`Bearer ${token}`);xhr.timeout=120000;if(xhr.upload&&onProgress)xhr.upload.onprogress=e=>{if(e.lengthComputable&&e.total>0)onProgress(Math.min(100,Math.round(e.loaded/e.total*100)));};xhr.onerror=()=>reject(new SellerApiError('Document uploads require an internet connection.',{offline:true}));xhr.ontimeout=()=>reject(new SellerApiError('The document upload took too long. Please retry.'));xhr.onload=()=>{let body:any={};try{body=JSON.parse(xhr.responseText||'{}');}catch{}if(xhr.status<200||xhr.status>=300)return reject(new SellerApiError(body?.error||'Unable to upload this document.',{status:xhr.status}));onProgress?.(100);resolve(body);};xhr.send(form);});}

export const documentService={
 list:(force=false)=>cachedGet<{documents:SellerDocument[]}>('documents','/api/seller/documents',{force,maxAgeMs:2*60_000}),
 async upload(asset:DocumentUploadAsset,values:{name?:string;category?:string;expiresAt?:number|null},onProgress?:(value:number)=>void){const user=auth.currentUser;if(!user)throw new SellerApiError('Your seller session has expired.',{status:401});const token=await user.getIdToken();const form=new FormData();form.append('file',{uri:asset.uri,name:asset.name,type:asset.mimeType||'application/octet-stream'} as any);if(values.name)form.append('name',values.name);if(values.category)form.append('category',values.category);if(values.expiresAt)form.append('expiresAt',String(values.expiresAt));const result=await uploadForm(form,token,onProgress);await Promise.all([invalidateCache('documents'),invalidateCache('overview')]);return result;},
 async remove(id:string){const result=await request<{success:true}>(`/api/seller/documents?id=${encodeURIComponent(id)}`,{method:'DELETE'});await Promise.all([invalidateCache('documents'),invalidateCache('overview')]);return result;},
 async downloadAndShare(document:SellerDocument){const user=auth.currentUser;if(!user)throw new SellerApiError('Your seller session has expired.',{status:401});const token=await user.getIdToken();const safeName=(document.name||'document').replace(/[^a-zA-Z0-9._-]+/g,'-');const extension=(document.type||'bin').toLowerCase();const target=`${FileSystem.cacheDirectory}auronix-${document.id}-${safeName}.${extension}`;const result=await FileSystem.downloadAsync(`${API_URL}/api/seller/documents/file?id=${encodeURIComponent(document.id)}`,target,{headers:{Authorization:`Bearer ${token}`}});if(result.status<200||result.status>=300)throw new SellerApiError('Unable to download this document.');if(!(await Sharing.isAvailableAsync()))return result.uri;await Sharing.shareAsync(result.uri,{dialogTitle:'Auronix Seller document',mimeType:document.contentType||undefined});return result.uri;},
};
