import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { GlassCard, IOSSpinner, Screen } from '@/components/ui';
import { useAppTheme } from '@/src/context/theme';
import { analyticsService, type SellerAnalyticsResponse } from '@/src/services/analytics-service';
import type { AppColors } from '@/src/theme';

function money(value: number | null) { return value === null ? '—' : `$${value.toLocaleString(undefined, { maximumFractionDigits: 0 })}`; }
export default function Analytics() {
  const { colors } = useAppTheme(); const styles = useMemo(() => createStyles(colors), [colors]);
  const [data, setData] = useState<SellerAnalyticsResponse | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [metric, setMetric] = useState<'revenue'|'profit'>('revenue');
  const load = useCallback(async (force=false) => { force ? setRefreshing(true) : setLoading(true); try { setData((await analyticsService.get(force)).data); setError(''); } catch(caught){setError(caught instanceof Error ? caught.message : 'Unable to load analytics.');} finally {setLoading(false);setRefreshing(false);} },[]);
  useFocusEffect(useCallback(()=>{void load(false);},[load]));
  const max = Math.max(1, ...(data?.series || []).map(point => Number(point[metric] || 0)));
  return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={22} color={colors.ink}/></Pressable><View><Text style={styles.kicker}>SELLER PERFORMANCE</Text><Text style={styles.title}>Analytics</Text></View></View>{loading&&!data?<View style={styles.loader}><IOSSpinner/></View>:<ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={colors.ink}/>} contentContainerStyle={styles.content}>
    {error?<Text style={styles.error}>{error}</Text>:null}
    {!data?.available?<GlassCard style={styles.notice}><Ionicons name="information-circle-outline" size={22} color={colors.accent}/><View style={{flex:1}}><Text style={styles.noticeTitle}>Financial analytics not connected yet</Text><Text style={styles.noticeBody}>Auronix will not invent revenue, orders or profit. Product-derived inventory and margin data below remains available where product costs exist.</Text></View></GlassCard>:null}
    <View style={styles.grid}>{[['Revenue',money(data?.metrics.revenue??null)],['Profit',money(data?.metrics.profit??null)],['Orders',data?.metrics.orders===null||data?.metrics.orders===undefined?'—':String(data.metrics.orders)],['Inventory',money(data?.metrics.inventoryValue??null)],['Avg margin',data?.metrics.averageMargin===null||data?.metrics.averageMargin===undefined?'—':`${data.metrics.averageMargin.toFixed(1)}%`],['Sell-through',data?.metrics.sellThrough===null||data?.metrics.sellThrough===undefined?'—':`${data.metrics.sellThrough.toFixed(1)}%`]].map(([label,value])=><GlassCard key={label} style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></GlassCard>)}</View>
    <GlassCard style={styles.chartCard}><View style={styles.chartHeader}><Text style={styles.sectionTitle}>Performance history</Text><View style={styles.switch}>{(['revenue','profit'] as const).map(item=><Pressable key={item} onPress={()=>setMetric(item)} style={[styles.chip,metric===item&&styles.chipActive]}><Text style={[styles.chipText,metric===item&&styles.chipTextActive]}>{item}</Text></Pressable>)}</View></View>{data?.available&&data.series.length?<View style={styles.chart}>{data.series.slice(-30).map((point,index)=><View key={index} style={[styles.bar,{height:Math.max(4,Number(point[metric]||0)/max*130)}]}/>)}</View>:<View style={styles.emptyChart}><Ionicons name="bar-chart-outline" size={27} color={colors.muted}/><Text style={styles.emptyText}>No recorded financial series yet.</Text></View>}</GlassCard>
    <Text style={styles.sectionTitle}>Product performance</Text>{data?.productPerformance.mostProfitable.length?<GlassCard>{data.productPerformance.mostProfitable.map((product,index)=><Pressable key={product.id} onPress={()=>router.push({pathname:'/products/[id]',params:{id:product.id}})} style={[styles.productRow,index>0&&styles.border]}><View style={{flex:1}}><Text style={styles.productTitle}>{product.name}</Text><Text style={styles.productMeta}>Estimated profit {product.estimatedProfit===null||product.estimatedProfit===undefined?'—':`$${product.estimatedProfit.toFixed(2)}`}</Text></View><Ionicons name="chevron-forward" size={17} color={colors.muted}/></Pressable>)}</GlassCard>:<GlassCard style={styles.emptyBox}><Text style={styles.emptyText}>Add product cost and selling-price data to unlock product performance.</Text></GlassCard>}
  </ScrollView>}</Screen>;
}
function createStyles(colors:AppColors){return StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:14,paddingTop:8,paddingBottom:14},back:{width:43,height:43,borderRadius:15,backgroundColor:colors.surfaceSoft,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},kicker:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:1.3},title:{color:colors.ink,fontSize:25,fontWeight:'900',marginTop:2},loader:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:18,paddingBottom:45,gap:14},error:{color:colors.danger,fontSize:10},notice:{padding:15,flexDirection:'row',gap:11},noticeTitle:{color:colors.ink,fontSize:12,fontWeight:'900'},noticeBody:{color:colors.muted,fontSize:9,lineHeight:14,marginTop:3},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},metric:{width:'48.5%',padding:15,minHeight:89},metricLabel:{color:colors.muted,fontSize:9,fontWeight:'800'},metricValue:{color:colors.ink,fontSize:21,fontWeight:'900',marginTop:8},chartCard:{padding:16},chartHeader:{gap:10},sectionTitle:{color:colors.ink,fontSize:18,fontWeight:'900'},switch:{flexDirection:'row',gap:6},chip:{paddingHorizontal:11,minHeight:31,borderRadius:999,justifyContent:'center',backgroundColor:colors.surfaceSoft},chipActive:{backgroundColor:colors.accentSoft},chipText:{color:colors.muted,fontSize:9,fontWeight:'800',textTransform:'capitalize'},chipTextActive:{color:colors.accent},chart:{height:145,flexDirection:'row',alignItems:'flex-end',gap:3,marginTop:12},bar:{flex:1,borderRadius:4,backgroundColor:colors.accent},emptyChart:{height:130,alignItems:'center',justifyContent:'center',gap:8},emptyText:{color:colors.muted,fontSize:10,lineHeight:15,textAlign:'center'},productRow:{minHeight:62,flexDirection:'row',alignItems:'center',paddingHorizontal:15},border:{borderTopWidth:1,borderTopColor:colors.border},productTitle:{color:colors.ink,fontSize:12,fontWeight:'800'},productMeta:{color:colors.muted,fontSize:9,marginTop:3},emptyBox:{padding:20}})}
