import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { GlassCard, IOSSpinner, PrimaryButton, Screen, StatusPill } from '@/components/ui';
import { useAppTheme } from '@/src/context/theme';
import { marketplaceService } from '@/src/services/marketplace-service';
import type { AppColors } from '@/src/theme';
import type { MarketplaceConnection } from '@/src/types';

const icons:Record<string,keyof typeof Ionicons.glyphMap>={amazon:'logo-amazon',walmart:'storefront-outline',ebay:'pricetags-outline'};
export default function Marketplaces(){const{colors}=useAppTheme();const styles=useMemo(()=>createStyles(colors),[colors]);const[items,setItems]=useState<MarketplaceConnection[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');
const load=useCallback(async(force=false)=>{setLoading(true);try{setItems((await marketplaceService.list(force)).data.connections||[]);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load marketplaces.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{void load(false);},[load]));
async function connect(item:MarketplaceConnection){setBusy(item.id);setError('');try{await marketplaceService.connect(item.id);await load(true);}catch(e){setError(e instanceof Error?e.message:'Unable to start connection.');}finally{setBusy('');}}
function disconnect(item:MarketplaceConnection){Alert.alert(`Disconnect ${item.name}?`,'Auronix will stop treating this marketplace as connected. Provider-side access may also need to be revoked separately.',[{text:'Cancel',style:'cancel'},{text:'Disconnect',style:'destructive',onPress:()=>void(async()=>{setBusy(item.id);try{await marketplaceService.disconnect(item.id);await load(true);}catch(e){setError(e instanceof Error?e.message:'Unable to disconnect marketplace.');}finally{setBusy('');}})()}]);}
return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={22} color={colors.ink}/></Pressable><View><Text style={styles.kicker}>MARKETPLACE CENTER</Text><Text style={styles.title}>Connections</Text></View></View>{loading&&!items.length?<View style={styles.loader}><IOSSpinner/></View>:<ScrollView contentContainerStyle={styles.content}><GlassCard style={styles.notice}><Ionicons name="shield-checkmark-outline" size={21} color={colors.success}/><View style={{flex:1}}><Text style={styles.noticeTitle}>Backend-only marketplace credentials</Text><Text style={styles.noticeBody}>Provider secrets and OAuth tokens never belong in the mobile bundle. A marketplace is shown as connected only when the Auronix backend has a legitimate connection record.</Text></View></GlassCard>{error?<Text style={styles.error}>{error}</Text>:null}{items.map(item=><GlassCard key={item.id} style={styles.card}><View style={styles.icon}><Ionicons name={icons[item.id]||'storefront-outline'} size={24} color={colors.accent}/></View><View style={{flex:1}}><View style={styles.top}><Text style={styles.name}>{item.name}</Text><StatusPill value={item.status}/></View><Text style={styles.meta}>{item.status==='connected'?`Last sync ${item.lastSyncAt?new Date(item.lastSyncAt).toLocaleString():'not recorded'}`:item.configured?item.oauthConfigured?'Authorization required':'OAuth redirect configuration incomplete':'Integration credentials not configured'}</Text></View>{item.status==='connected'?<PrimaryButton tone="danger" style={styles.action} loading={busy===item.id} onPress={()=>disconnect(item)}><Ionicons name="unlink-outline" size={17} color={colors.danger}/></PrimaryButton>:<PrimaryButton tone="quiet" style={styles.action} loading={busy===item.id} onPress={()=>void connect(item)}><Ionicons name="link-outline" size={17} color={colors.accent}/></PrimaryButton>}</GlassCard>)}<Text style={styles.foot}>Orders, listings, inventory, revenue and account health remain unavailable until each provider is genuinely connected.</Text></ScrollView>}</Screen>}
function createStyles(colors:AppColors){return StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:14,paddingTop:8,paddingBottom:14},back:{width:43,height:43,borderRadius:15,backgroundColor:colors.surfaceSoft,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},kicker:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:1.3},title:{color:colors.ink,fontSize:25,fontWeight:'900',marginTop:2},loader:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:18,paddingBottom:45,gap:11},notice:{padding:15,flexDirection:'row',gap:10},noticeTitle:{color:colors.ink,fontSize:12,fontWeight:'900'},noticeBody:{color:colors.muted,fontSize:9,lineHeight:14,marginTop:3},error:{color:colors.danger,fontSize:10},card:{padding:14,flexDirection:'row',alignItems:'center',gap:11},icon:{width:50,height:50,borderRadius:17,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},top:{flexDirection:'row',alignItems:'center',gap:8},name:{color:colors.ink,fontSize:15,fontWeight:'900',flex:1},meta:{color:colors.muted,fontSize:9,lineHeight:14,marginTop:5},action:{width:44,minHeight:42,paddingHorizontal:0},foot:{color:colors.muted,fontSize:9,lineHeight:14,textAlign:'center',paddingHorizontal:15}})}
