import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { GlassCard, IOSSpinner, PrimaryButton, Screen, StatusPill, useUIStyles } from '@/components/ui';
import { useAppTheme } from '@/src/context/theme';
import { supplierService } from '@/src/services/supplier-service';
import type { AppColors } from '@/src/theme';
import type { Supplier } from '@/src/types';

export default function Suppliers() {
  const { colors } = useAppTheme(); const ui = useUIStyles(); const styles = useMemo(()=>createStyles(colors),[colors]);
  const [items,setItems]=useState<Supplier[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({name:'',contact:'',email:'',website:'',notes:''});
  const load=useCallback(async(force=false)=>{setLoading(true);try{setItems((await supplierService.list(force)).data.suppliers||[]);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load suppliers.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load(false);},[load]));
  async function save(){if(!form.name.trim())return setError('Supplier name is required.');setBusy(true);try{await supplierService.create(form);setForm({name:'',contact:'',email:'',website:'',notes:''});setShow(false);await load(true);}catch(e){setError(e instanceof Error?e.message:'Unable to create supplier.');}finally{setBusy(false);}}
  function remove(item:Supplier){Alert.alert('Delete supplier?',`${item.name} will be removed from your supplier directory. Product and catalog records are not deleted.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void(async()=>{try{await supplierService.remove(item.id);await load(true);}catch(e){setError(e instanceof Error?e.message:'Unable to delete supplier.');}})()}]);}
  return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={22} color={colors.ink}/></Pressable><View style={{flex:1}}><Text style={styles.kicker}>SUPPLIER DIRECTORY</Text><Text style={styles.title}>Suppliers</Text></View><PrimaryButton style={styles.add} onPress={()=>setShow(true)}><Ionicons name="add" size={22} color={colors.inverse}/></PrimaryButton></View>
    {error&&!show?<Text style={styles.error}>{error}</Text>:null}{loading&&!items.length?<View style={styles.loader}><IOSSpinner/></View>:<FlatList data={items} keyExtractor={item=>item.id} contentContainerStyle={[styles.list,!items.length&&{flexGrow:1}]} ListEmptyComponent={<View style={styles.empty}><Ionicons name="business-outline" size={35} color={colors.muted}/><Text style={styles.emptyTitle}>No suppliers yet</Text><Text style={styles.emptyBody}>Add suppliers to connect product and catalog records to a real source.</Text><PrimaryButton onPress={()=>setShow(true)}>Add Supplier</PrimaryButton></View>} renderItem={({item})=><GlassCard style={styles.card}><View style={styles.icon}><Ionicons name="business-outline" size={20} color={colors.accent}/></View><View style={{flex:1}}><View style={styles.top}><Text style={styles.name}>{item.name}</Text><StatusPill value={item.approvalStatus||'Not reviewed'}/></View><Text style={styles.meta}>{[item.contact,item.email,item.website].filter(Boolean).join(' · ')||'No contact details yet'}</Text><Text style={styles.counts}>{item.productCount||0} products · {item.catalogCount||0} catalogs</Text></View><Pressable hitSlop={10} onPress={()=>remove(item)}><Ionicons name="trash-outline" size={18} color={colors.muted}/></Pressable></GlassCard>}/>} 
    <Modal visible={show} transparent animationType="slide" onRequestClose={()=>!busy&&setShow(false)}><View style={styles.overlay}><GlassCard style={styles.sheet}><View style={styles.sheetHead}><Text style={ui.sectionTitle}>Add supplier</Text><Pressable onPress={()=>setShow(false)}><Ionicons name="close-circle" size={29} color={colors.muted}/></Pressable></View>{(['name','contact','email','website'] as const).map(key=><View key={key} style={{gap:6}}><Text style={ui.label}>{key}</Text><TextInput value={form[key]} onChangeText={value=>setForm({...form,[key]:value})} style={ui.input} placeholder={key==='name'?'Supplier name':key} placeholderTextColor={colors.muted} autoCapitalize={key==='email'||key==='website'?'none':'sentences'} keyboardType={key==='email'?'email-address':key==='website'?'url':'default'}/></View>)}<Text style={ui.label}>Notes</Text><TextInput value={form.notes} onChangeText={notes=>setForm({...form,notes})} multiline style={[ui.input,ui.textarea]} placeholder="Optional supplier notes" placeholderTextColor={colors.muted}/>{error?<Text style={styles.modalError}>{error}</Text>:null}<PrimaryButton loading={busy} onPress={save}>Save Supplier</PrimaryButton></GlassCard></View></Modal>
  </Screen>;
}
function createStyles(colors:AppColors){return StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:14,paddingTop:8,paddingBottom:14},back:{width:43,height:43,borderRadius:15,backgroundColor:colors.surfaceSoft,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},add:{width:43,minHeight:43,paddingHorizontal:0},kicker:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:1.3},title:{color:colors.ink,fontSize:25,fontWeight:'900',marginTop:2},error:{color:colors.danger,fontSize:10,marginHorizontal:18},loader:{flex:1,alignItems:'center',justifyContent:'center'},list:{padding:18,paddingBottom:45,gap:10},card:{padding:14,flexDirection:'row',alignItems:'center',gap:11},icon:{width:46,height:46,borderRadius:16,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},top:{flexDirection:'row',alignItems:'center',gap:8},name:{flex:1,color:colors.ink,fontSize:14,fontWeight:'900'},meta:{color:colors.muted,fontSize:9,marginTop:5},counts:{color:colors.accent,fontSize:9,fontWeight:'800',marginTop:6},empty:{flex:1,minHeight:420,alignItems:'center',justifyContent:'center',gap:10,padding:30},emptyTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},emptyBody:{color:colors.muted,fontSize:11,lineHeight:17,textAlign:'center',marginBottom:5},overlay:{flex:1,backgroundColor:colors.overlay,justifyContent:'flex-end'},sheet:{padding:18,paddingBottom:34,borderBottomLeftRadius:0,borderBottomRightRadius:0,gap:10},sheetHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:4},modalError:{color:colors.danger,fontSize:10}})}
