import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { GlassCard, Header, IOSSpinner, PrimaryButton, Screen, StatusPill, ui } from '@/components/ui';
import { useAuth } from '@/src/context/auth';
import { sellerApi } from '@/src/lib/api';
import { colors } from '@/src/theme';
import type { SellerProfile } from '@/src/types';

export default function Account() {
  const { user, logout } = useAuth(); const [profile, setProfile] = useState<SellerProfile | null>(null); const [form, setForm] = useState({ displayName: '', businessName: '', phone: '', website: '' }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { try { const p = (await sellerApi.workspace()).profile; setProfile(p); setForm({ displayName: p.displayName || p.name || '', businessName: p.businessName || '', phone: p.phone || '', website: p.website || '' }); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  async function save() { setBusy(true); setMessage(''); try { await sellerApi.updateProfile(form); setMessage('Profile updated.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to update profile.'); } finally { setBusy(false); } }
  async function exit() { await logout(); router.replace('/login'); }
  return <Screen><Header eyebrow="SECURE SELLER PROFILE" title="Account" />{loading ? <View style={styles.loader}><IOSSpinner /></View> : <ScrollView contentContainerStyle={ui.content} keyboardShouldPersistTaps="handled"><GlassCard style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>{(profile?.displayName || profile?.name || user?.email || 'A').slice(0, 1).toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{profile?.displayName || profile?.name || 'Auronix Seller'}</Text><Text style={styles.email}>{user?.email}</Text></View><StatusPill value={profile?.status || 'Active'} /></GlassCard><GlassCard style={styles.form}><Text style={ui.label}>Display name</Text><TextInput style={ui.input} value={form.displayName} onChangeText={(displayName) => setForm({ ...form, displayName })} /><Text style={ui.label}>Business name</Text><TextInput style={ui.input} value={form.businessName} onChangeText={(businessName) => setForm({ ...form, businessName })} /><Text style={ui.label}>Phone</Text><TextInput keyboardType="phone-pad" style={ui.input} value={form.phone} onChangeText={(phone) => setForm({ ...form, phone })} /><Text style={ui.label}>Website</Text><TextInput autoCapitalize="none" keyboardType="url" style={ui.input} value={form.website} onChangeText={(website) => setForm({ ...form, website })} />{message ? <Text style={[styles.message, message === 'Profile updated.' && { color: colors.success }]}>{message}</Text> : null}<PrimaryButton loading={busy} onPress={save}>Save profile</PrimaryButton></GlassCard><PrimaryButton tone="danger" onPress={exit}><View style={ui.row}><Ionicons name="log-out-outline" color={colors.danger} size={19} /><Text style={styles.logout}>Sign out</Text></View></PrimaryButton></ScrollView>}</Screen>;
}
const styles = StyleSheet.create({ loader: { flex: 1, justifyContent: 'center', alignItems: 'center' }, identity: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 13 }, avatar: { width: 49, height: 49, borderRadius: 17, backgroundColor: colors.accentStrong, justifyContent: 'center', alignItems: 'center' }, avatarText: { color: '#fff', fontWeight: '900', fontSize: 20 }, name: { color: colors.ink, fontWeight: '800', fontSize: 16 }, email: { color: colors.muted, fontSize: 11, marginTop: 3 }, form: { padding: 18, gap: 10 }, message: { color: colors.danger, fontSize: 12 }, logout: { color: colors.danger, fontWeight: '700', marginLeft: 8 } });
