import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { IOSSpinner, Screen } from '@/components/ui';
import { askAuronix } from '@/src/lib/api';
import { colors } from '@/src/theme';

type Message = { role: 'user' | 'assistant'; content: string };
const prompts = ['Check my seller status', 'Help with verification', 'Create a support ticket'];
export default function Chat() {
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: 'Hi, I’m Auronix AI. I can help with seller access, applications, products, policies, and support. What do you need help with?' }]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const list = useRef<ScrollView>(null);
  async function send(value = input) { const text = value.trim(); if (!text || busy) return; if (/create.{0,20}(ticket|support request)/i.test(text)) { router.push('/support/new-ticket'); return; } const next: Message[] = [...messages, { role: 'user', content: text }]; setMessages(next); setInput(''); setBusy(true); try { const result = await askAuronix(next.slice(-16)); setMessages([...next, { role: 'assistant', content: result.response || result.error || 'I could not answer that right now.' }]); } catch (e) { setMessages([...next, { role: 'assistant', content: e instanceof Error ? e.message : 'Auronix AI is temporarily unavailable.' }]); } finally { setBusy(false); setTimeout(() => list.current?.scrollToEnd({ animated: true }), 50); } }
  return <Screen><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.headerButton}><Ionicons name="chevron-back" size={24} color={colors.ink} /></Pressable><View style={styles.aiMark}><Ionicons name="sparkles" size={18} color="#fff" /></View><View style={{ flex: 1 }}><Text style={styles.headerTitle}>Auronix AI</Text><Text style={styles.headerMeta}>Support assistant · Online</Text></View><Pressable onPress={() => setMessages(messages.slice(0, 1))} style={styles.headerButton}><Ionicons name="refresh" size={20} color={colors.muted} /></Pressable></View><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={8} style={{ flex: 1 }}><ScrollView ref={list} onContentSizeChange={() => list.current?.scrollToEnd({ animated: true })} contentContainerStyle={styles.messages} keyboardShouldPersistTaps="handled">{messages.map((message, index) => <View key={index} style={[styles.message, message.role === 'user' ? styles.userMessage : styles.aiMessage]}><Text style={styles.role}>{message.role === 'user' ? 'YOU' : 'AURONIX AI'}</Text><Text selectable style={styles.messageText}>{message.content}</Text></View>)}{busy ? <View style={[styles.message, styles.aiMessage, styles.typing]}><IOSSpinner size={20} /><Text style={styles.thinking}>Thinking…</Text></View> : null}</ScrollView>{messages.length === 1 ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.prompts}>{prompts.map((prompt) => <Pressable key={prompt} onPress={() => send(prompt)} style={styles.prompt}><Text style={styles.promptText}>{prompt}</Text></Pressable>)}</ScrollView> : null}<View style={styles.composer}><TextInput multiline maxLength={4000} value={input} onChangeText={setInput} placeholder="Message Auronix AI…" placeholderTextColor="#657186" style={styles.input} /><Pressable disabled={!input.trim() || busy} onPress={() => send()} style={[styles.send, (!input.trim() || busy) && { opacity: .4 }]}>{busy ? <IOSSpinner size={20} /> : <Ionicons name="arrow-up" color="#fff" size={22} />}</Pressable></View><Text style={styles.disclosure}>Auronix AI can make mistakes. Confirm important account information in your seller workspace.</Text></KeyboardAvoidingView></Screen>;
}
const styles = StyleSheet.create({ header: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, headerButton: { width: 42, height: 42, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.055)' }, aiMark: { width: 40, height: 40, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accentStrong }, headerTitle: { color: colors.ink, fontWeight: '800', fontSize: 15 }, headerMeta: { color: colors.success, fontSize: 10, marginTop: 2 }, messages: { padding: 15, gap: 12, paddingBottom: 25 }, message: { maxWidth: '88%', borderRadius: 21, padding: 15, borderWidth: 1 }, aiMessage: { alignSelf: 'flex-start', backgroundColor: 'rgba(255,255,255,.065)', borderColor: colors.border, borderBottomLeftRadius: 7 }, userMessage: { alignSelf: 'flex-end', backgroundColor: colors.accentStrong, borderColor: 'rgba(255,255,255,.13)', borderBottomRightRadius: 7 }, role: { color: 'rgba(255,255,255,.55)', fontSize: 8, letterSpacing: 1.1, fontWeight: '800', marginBottom: 6 }, messageText: { color: colors.ink, fontSize: 14, lineHeight: 21 }, typing: { flexDirection: 'row', alignItems: 'center', gap: 9 }, thinking: { color: colors.muted, fontSize: 12 }, prompts: { gap: 8, paddingHorizontal: 14, paddingBottom: 9 }, prompt: { paddingHorizontal: 14, minHeight: 39, justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 999, backgroundColor: 'rgba(255,255,255,.045)' }, promptText: { color: colors.ink, fontSize: 11, fontWeight: '600' }, composer: { marginHorizontal: 11, borderRadius: 23, backgroundColor: 'rgba(255,255,255,.08)', borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'flex-end', padding: 6, paddingLeft: 15 }, input: { flex: 1, minHeight: 44, maxHeight: 120, color: colors.ink, fontSize: 15, paddingTop: 11, paddingBottom: 10 }, send: { width: 43, height: 43, borderRadius: 16, backgroundColor: colors.accentStrong, alignItems: 'center', justifyContent: 'center' }, disclosure: { color: colors.muted, textAlign: 'center', fontSize: 9, paddingVertical: 7, paddingHorizontal: 18 } });
